spring:
  profiles:
    active: dev
springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api
application:
  security:
    jwt:
      secret-key: ${jwt-secret-pass}
      expiration: 8640000