version: '3.8'
x-common-variables: &common-variables
  MYSQL_DATABASE: db_mdd

services:
  mysql_server:
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-pass
      MYSQL_USER: dba
      <<: *common-variables
    secrets:
      - mysql-root-pass
    networks:
      - spring-boot-app-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql_server
    depends_on:
      - mysql_server
    networks:
      - spring-boot-app-network

  mdd-api:
    image: springboot-mdd-api:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      JWT_SECRET_FILE: /run/secrets/jwt-secret-pass
      MYSQL_HOST: mysql_server
      MYSQL_PORT: 3306
      <<: *common-variables
    secrets:
      - mysql-root-pass
      - jwt-secret-pass
    networks:
      - spring-boot-app-network

volumes:
  mysql-data:

networks:
  spring-boot-app-network:

secrets:
  mysql-root-pass:
    external: true
  jwt-secret-pass:
    external: true